import React from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { X, Smartphone, CheckCircle2 } from 'lucide-react';
import { useI18n } from './I18nProvider';

interface ClawBotModalProps {
  onClose: () => void;
}

export function ClawBotModal({ onClose }: ClawBotModalProps) {
  const { t } = useI18n();
  // Mock webhook URL that would normally be generated by the local Go server
  const webhookUrl = "https://clawbot.wechat.com/bind?token=local-fragnote-12345";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 backdrop-blur-sm">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-md overflow-hidden relative animate-in fade-in zoom-in-95 duration-200">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 transition-colors"
        >
          <X size={20} />
        </button>

        <div className="p-8 text-center">
          <div className="w-12 h-12 bg-green-50 text-green-600 rounded-full flex items-center justify-center mx-auto mb-4">
            <Smartphone size={24} />
          </div>

          <h2 className="text-xl font-semibold text-gray-900 mb-2">{t('connectWeChat')}</h2>
          <p className="text-sm text-gray-500 mb-8">
            {t('wechatIntro')}
          </p>

          <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm inline-block mb-8">
            <QRCodeSVG
              value={webhookUrl}
              size={180}
              level="H"
              includeMargin={false}
            />
          </div>

          <div className="space-y-3 text-left bg-gray-50 p-4 rounded-lg">
            <h3 className="text-xs font-semibold text-gray-900 uppercase tracking-wider">{t('howItWorks')}</h3>
            <ul className="text-sm text-gray-600 space-y-2">
              <li className="flex items-start gap-2">
                <CheckCircle2 size={16} className="text-green-500 shrink-0 mt-0.5" />
                <span>{t('wechatStep1')}</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 size={16} className="text-green-500 shrink-0 mt-0.5" />
                <span>{t('wechatStep2')}</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 size={16} className="text-green-500 shrink-0 mt-0.5" />
                <span>{t('wechatStep3')}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
