import React from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { X, Smartphone, CheckCircle2 } from 'lucide-react';

interface ClawBotModalProps {
  onClose: () => void;
}

export function ClawBotModal({ onClose }: ClawBotModalProps) {
  // Mock webhook URL that would normally be generated by the local Go server
  const webhookUrl = "https://clawbot.wechat.com/bind?token=local-fragnote-12345";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 backdrop-blur-sm">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-md overflow-hidden relative animate-in fade-in zoom-in-95 duration-200">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 transition-colors"
        >
          <X size={20} />
        </button>

        <div className="p-8 text-center">
          <div className="w-12 h-12 bg-green-50 text-green-600 rounded-full flex items-center justify-center mx-auto mb-4">
            <Smartphone size={24} />
          </div>

          <h2 className="text-xl font-semibold text-gray-900 mb-2">Connect WeChat ClawBot</h2>
          <p className="text-sm text-gray-500 mb-8">
            Scan this QR code with WeChat to bind your phone. Messages sent to the bot will be saved directly to your local drive.
          </p>

          <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm inline-block mb-8">
            <QRCodeSVG
              value={webhookUrl}
              size={180}
              level="H"
              includeMargin={false}
            />
          </div>

          <div className="space-y-3 text-left bg-gray-50 p-4 rounded-lg">
            <h3 className="text-xs font-semibold text-gray-900 uppercase tracking-wider">How it works</h3>
            <ul className="text-sm text-gray-600 space-y-2">
              <li className="flex items-start gap-2">
                <CheckCircle2 size={16} className="text-green-500 shrink-0 mt-0.5" />
                <span>Send text or voice to the ClawBot in WeChat.</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 size={16} className="text-green-500 shrink-0 mt-0.5" />
                <span>It instantly syncs to your local <code>TFO_Data</code> folder.</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 size={16} className="text-green-500 shrink-0 mt-0.5" />
                <span>Zero cloud storage. 100% private.</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
